
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import FiatCMTATokenContractArtifactJson from '../../target/token_contract-FiatCMTAToken.json' with { type: 'json' };
export const FiatCMTATokenContractArtifact = loadContractArtifact(FiatCMTATokenContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract FiatCMTAToken;
 */
export class FiatCMTATokenContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, FiatCMTATokenContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, FiatCMTATokenContract.artifact, wallet) as Promise<FiatCMTATokenContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, tokenName: string, symbol: string, tokenCurrency: string, decimals: (bigint | number), admin: AztecAddressLike) {
    return new DeployMethod<FiatCMTATokenContract>(PublicKeys.default(), wallet, FiatCMTATokenContractArtifact, FiatCMTATokenContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, tokenName: string, symbol: string, tokenCurrency: string, decimals: (bigint | number), admin: AztecAddressLike) {
    return new DeployMethod<FiatCMTATokenContract>(publicKeys, wallet, FiatCMTATokenContractArtifact, FiatCMTATokenContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof FiatCMTATokenContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<FiatCMTATokenContract['methods'][M]>
  ) {
    return new DeployMethod<FiatCMTATokenContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      FiatCMTATokenContractArtifact,
      FiatCMTATokenContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return FiatCMTATokenContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(FiatCMTATokenContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'pause_module' | 'validation_module' | 'enforcement_module' | 'access_control' | 'issuer_address' | 'balances' | 'total_supply' | 'symbol' | 'tokenName' | 'tokenCurrency' | 'decimals'> {
      return {
        pause_module: {
      slot: new Fr(1n),
    },
validation_module: {
      slot: new Fr(2n),
    },
enforcement_module: {
      slot: new Fr(11n),
    },
access_control: {
      slot: new Fr(12n),
    },
issuer_address: {
      slot: new Fr(13n),
    },
balances: {
      slot: new Fr(17n),
    },
total_supply: {
      slot: new Fr(18n),
    },
symbol: {
      slot: new Fr(19n),
    },
tokenName: {
      slot: new Fr(21n),
    },
tokenCurrency: {
      slot: new Fr(23n),
    },
decimals: {
      slot: new Fr(25n),
    }
      } as ContractStorageLayout<'pause_module' | 'validation_module' | 'enforcement_module' | 'access_control' | 'issuer_address' | 'balances' | 'total_supply' | 'symbol' | 'tokenName' | 'tokenCurrency' | 'decimals'>;
    }
    

  public static get notes(): ContractNotes<'UintNote' | 'ValueNote'> {
    return {
      UintNote: {
          id: new NoteSelector(0),
        },
ValueNote: {
          id: new NoteSelector(1),
        }
    } as ContractNotes<'UintNote' | 'ValueNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_to_list(newListAddress: struct, userFlag: struct) */
    add_to_list: ((newListAddress: AztecAddressLike, userFlag: { is_blacklisted: boolean, is_whitelisted: boolean, is_in_sanction_list: boolean }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** balance_of_private(owner: struct) */
    balance_of_private: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn(from: struct, amount: field, nonce: field) */
    burn: ((from: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn_batch(accounts: array, amount: array, nonce: field) */
    burn_batch: ((accounts: AztecAddressLike[], amount: FieldLike[], nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_authwit(inner_hash: field) */
    cancel_authwit: ((inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(tokenName: string, symbol: string, tokenCurrency: string, decimals: integer, admin: struct) */
    constructor: ((tokenName: string, symbol: string, tokenCurrency: string, decimals: (bigint | number), admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** freeze(user: struct, value: struct) */
    freeze: ((user: AztecAddressLike, value: { is_freezed: boolean }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_frozen(user: struct) */
    get_frozen: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_operations() */
    get_operations: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** grant_role(role: field, account: struct) */
    grant_role: ((role: FieldLike, account: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** has_role(role: field, account: struct) */
    has_role: ((role: FieldLike, account: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint(to: struct, amount: field) */
    mint: ((to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_batch(accounts: array, amount: array) */
    mint_batch: ((accounts: AztecAddressLike[], amount: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** only_role(role: field, caller: struct) */
    only_role: ((role: FieldLike, caller: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pause_contract() */
    pause_contract: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_get_currency() */
    private_get_currency: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_get_decimals() */
    private_get_decimals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_get_issuer() */
    private_get_issuer: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_get_name() */
    private_get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_get_symbol() */
    private_get_symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_currency() */
    public_get_currency: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_decimals() */
    public_get_decimals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_issuer() */
    public_get_issuer: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_name() */
    public_get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_pause() */
    public_get_pause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_symbol() */
    public_get_symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_from_list(removeListAddress: struct, userFlag: struct) */
    remove_from_list: ((removeListAddress: AztecAddressLike, userFlag: { is_blacklisted: boolean, is_whitelisted: boolean, is_in_sanction_list: boolean }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** renounce_role(role: field, callerConfirmation: struct) */
    renounce_role: ((role: FieldLike, callerConfirmation: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** revoke_role(role: field, account: struct) */
    revoke_role: ((role: FieldLike, account: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_operations(operations: struct) */
    set_operations: ((operations: { operate_blacklist: boolean, operate_whitelist: boolean, operate_sanctionlist: boolean }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** total_supply() */
    total_supply: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer(to: struct, amount: field) */
    transfer: ((to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_batch(accounts: array, amount: array, nonce: field) */
    transfer_batch: ((accounts: AztecAddressLike[], amount: FieldLike[], nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_from(from: struct, to: struct, amount: field, nonce: field) */
    transfer_from: ((from: AztecAddressLike, to: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unfreeze(user: struct, value: struct) */
    unfreeze: ((user: AztecAddressLike, value: { is_freezed: boolean }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unpause_contract() */
    unpause_contract: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
